source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'rspec-rails'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'haml-rails', '>= 0.3.4'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'lodash-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc
# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use debugger
gem 'debugger', group: [:development, :test]

gem "devise"
gem "pry", group: [:development, :test]
gem "pry-debugger",  group: [:development, :test]

group :test do
  gem 'cucumber-rails', :require => false
  # database_cleaner is not required, but highly recommended
  gem 'database_cleaner'
end
